services:
  django:
    build:
      context: ./atlascope_django
      dockerfile: Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000
    volumes:
      - ./atlascope_django:/app
      - ./data:/data
    working_dir: /app
  vue:
    image: node:latest
    command: ["npm", "run", "serve"]
    ports:
      - 3000:3000
    volumes:
      - ./atlascope_vue:/web
    working_dir: /web
    environment:
      - API_ROOT=http://localhost:8000/api/
