# Generated by Django 5.2.4 on 2025-08-21 13:59

import django.core.files.storage
import django.db.models.deletion
import pathlib
import tcga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMAPTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('column_names', models.JSONField(default=tcga.models.get_vector_columns)),
                ('umap_kwargs', models.JSONField(default=tcga.models.get_default_umap_kwargs)),
                ('pickled', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/data/transforms')), upload_to='')),
                ('fitted_cells', models.ManyToManyField(to='tcga.cell')),
            ],
        ),
        migrations.CreateModel(
            name='UMAPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scatterplot_data', models.JSONField()),
                ('transformed_cells', models.ManyToManyField(to='tcga.cell')),
                ('transform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcga.umaptransform')),
            ],
        ),
    ]
