# Generated by Django 5.2.5 on 2025-08-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcga', '0003_remove_cell_vector_text_cell_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='vector_text',
        ),
        migrations.AlterField(
            model_name='cell',
            name='vector',
            field=models.JSONField(default=list),
        ),
    ]
