name: style
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-client:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: cd web && npm i && npm run lint
